apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: llxsl03zh-go
  janus-idp.io/tekton: llxsl03zh-go
  backstage.io/kubernetes-id: llxsl03zh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: llxsl03zh-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
