apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: llxsl03zh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: llxsl03zh-go 
  name: llxsl03zh-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: llxsl03zh-go
    weight: 100 
