apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: llxsl03zh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: llxsl03zh-go 
  name: llxsl03zh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: llxsl03zh-go 
